### ISSUE TITLE
5.0.0.M1  WEEKLY GOALS

### ISSUE THREAD

**Issue by jgrandja** [jgrandja/oauth2-samples#47]
## **Jan 2 - 6**
- [x] #2 Add Integration Tests
- [x] #6 Simplify Java Configuration
- [x] #37 Add authorizeUri attribute in AuthorizationRequestAttributes

## **Jan 9 - 13**
- [x] #49 Delete AuthorizationRequestRedirectFilter's AuthorizationRequestMatcher
- [x] #50 Remove the protected methods in AuthorizationRequestRedirectFilter
- [x] #56 Ensure Domain Objects match specification
- [ ] #8 Remove AuthorizationRequestRedirectStrategy in favor of AuthenticationEntryPoint
- [x] #29 Establish OAuth2 Exception hierarchy
- [x] #31 Provide support for authorization_code grant type
- [x] #62 Create OAuth2ClientSecurityConfigurer

## **Jan 16 - 20**
- [x] #7 We should generate a log in page for the user
- [x] #44 Provide generic impl of AuthorizationRequestUriBuilder
- [x] #43 Remove TODO's in ClientRegistration
- [x] #42 Remove TODO's in AuthorizationCodeGrantAuthenticationProvider
- [x] #40 Remove TODO's in OpenIDConnectUser
- [x] #39 Remove TODO's in OAuth2User

## **Jan 23 - 27**
- [x] #30 Provide support for custom UserDetails
- [x] #26 Login using UAA
- [ ] #28 Login using LinkedIn
- [x] #27 Login using Facebook

## **Jan 30 - Feb 3**
- [ ] #41 Separate OAuth2 Client code from sample project
- [ ] #23 Add Unit Tests

## **Feb 6 - 7**
- [ ] Clean-up / Polish
- [ ] Merge into Spring Security
